.PHONY: clean All

All:
	@echo "----------Building project:[ DDLC - Debug ]----------"
	@"$(MAKE)" -f  "DDLC.mk"
clean:
	@echo "----------Cleaning project:[ DDLC - Debug ]----------"
	@"$(MAKE)" -f  "DDLC.mk" clean
